name: Deploy to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your project in the repository
  PYTHON_VERSION: '3.11' # Python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: 'Zip artifacts for deployment'
        run: zip -r release.zip ./* --exclude='*.git*' --exclude='venv/*'

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'Forex521' # Replace with your Azure Function App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_784F12FCB5F244BF9826EAC9B72DB1E7 }}
          package: release.zip
          scm-do-build-during-deployment: true # You might not need this if you're deploying a Python function that doesn't require building on Azure
          enable-oryx-build: true
