name: Deploy to Azure Functions

on:
  push:
    branches:
    - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Set this to the Python version you are using

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: 'Forex521'  #Azure Function App name
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_784F12FCB5F244BF9826EAC9B72DB1E7 }}
        package: .  # The path to your function app's directory in the repository

 
